### PR TITLE
Linux 3.10 compatibility

### PR DESCRIPTION
**Pull request by nowrep**
create_proc_entry() is no longer available in 3.10
also fixed warning issue on x86_64

### CODE REVIEW

**Comment by nowrep** [comment]
Oops, I overlooked this ..

``` diff
diff --git a/acpi_call.c b/acpi_call.c
index 4afd9db..3025d97 100644
--- a/acpi_call.c
+++ b/acpi_call.c
@@ -309,9 +309,6 @@ static ssize_t acpi_proc_read( struct file *filp, char __user *buff,
     int len = strlen(result_buffer);

     // output the current result buffer
-    if (copy_to_user(buff, result_buffer, len + 1))
-        return -EFAULT;
-
     ret = simple_read_from_buffer(buff, count, off, result_buffer, len + 1);

     // initialize the result buffer for later
```

**Comment by avilella** [comment]
Is this a pull request?

**Comment by nowrep** [comment]
It's just a minor change, I'll prefer if you just commit it yourself.
But of course, I can open another pull request if you want.

**Comment by avilella** [comment]
please do a pull request, I'll just accept it.

**Pull request merged**
